### ISSUE TITLE
Bug? Sorting weird in Journal_Internal example

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#113]
Col1 and 2, I think ASC/DESC is backwards?
Col3, it's like it organized them, but not alphabetically?

https://user-images.githubusercontent.com/57631333/222769425-874d2ced-7df4-4e6c-b892-04261713a1b5.mp4

**Comment by PySimpleSQL** [comment]
Aah ok.  Its sorting based on the primary key number, and not the description string! I'll take a look
