### ISSUE TITLE
Switch ASC / DESC unicode marker

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#115]
In thunderbird:
![image](https://user-images.githubusercontent.com/57631333/222811038-ec29c327-853a-42aa-95a7-dd4b9bd9d3a7.png)
![image](https://user-images.githubusercontent.com/57631333/222811493-b87032cc-2f7c-4f47-b98a-253da7feab46.png)

In pysimplegui
![image](https://user-images.githubusercontent.com/57631333/222811165-7e6b9446-161f-4a95-acc3-50d0184fbf3c.png)
![image](https://user-images.githubusercontent.com/57631333/222811243-04da2711-4855-4052-9d79-0c2bb8075f7a.png)

Do we want to flip that?

**Comment by PySimpleSQL** [comment]
Hmm, I'm not sure.  To me, the way it is now looks correct - i'll try to look for more examples

**Comment by PySimpleSQL** [comment]
I just checked real quick on the raspberry pi i'm working off of, and it matches the pysimplesql sort markers.  I didn't realize there was variation in how this was presented

![DeepinScreenshot_select-area_20230303182918](https://user-images.githubusercontent.com/70232210/222854381-2a6191d8-8878-4e5e-b0e3-f31e2791f1eb.png)
![DeepinScreenshot_select-area_20230303182955](https://user-images.githubusercontent.com/70232210/222854389-f3203f78-23cd-4389-ae3b-d392f04423cc.png)

**Comment by PySimpleSQL** [comment]
Plus, the end user can change it via a ThemePack if they want :)

**Comment by ssweber** [comment]
Yeah. I’m thinking that some use it as a pyramid (a at bottom, z at top), while thunderbird uses it as less than, greater than

**Comment by ssweber** [comment]
I thought you'd get a laugh from reading[ this stack exchange](https://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header)

I had no idea people were so passionate about which way was right!
