### ISSUE TITLE
Checkbox handling

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#118]
What logic have you included to try to handle checkboxes? I’m assuming some of your sql_type casting?

It’s almost like we shouldn’t include any logic, and have the user set our recommended transforms based on their setup.

either int (0/1), Boolean, text (True/False) and messier ones (n/y),(x,””)

then need to call transforms in insert & records_changed.

**Comment by ssweber** [comment]
Before we dig into it, I’ll make a checkbox example that has all the data types (with defaults and no defaults) so I can demonstrate

**Comment by PySimpleSQL** [comment]
Yes, everything now runs through the sql_type casting for the purpose of checking for dirty records, and just before save.  I.e. the type value during runtime is whatever PySimpleGUI uses.

Are you having an issue with checkboxes?

if you want to typecast yourself:
casted_cb_val = frm['Journal'].column_info['cb_column'].cast(win['cb_obj])

**Comment by PySimpleSQL** [comment]
Looks like this is fixed in your pull request.  Thanks!
