### ISSUE TITLE
Bug when switching saving row on prompt_save

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#121]
I tried to work out how to fix this, but now its getting too late.

Basically, when switching rows on a prompt_save, if you say 'Yes', it switches back to the row you were just on. But not all the information is updated.

https://user-images.githubusercontent.com/57631333/222944556-68185ea1-1f1b-499d-b524-1c1e2fd90029.mp4

**Comment by PySimpleSQL** [comment]
fixing this next.  It's related to the records_changed() change from earlier.  I think I may put the default back to True

**Comment by PySimpleSQL** [comment]
changing the records_changed default back to True fixed some of the issue.  Now the elements update.  Now just to find what is stopping the record from switching

**Comment by PySimpleSQL** [comment]
actually, it looks like it's fixed - I can no longer reproduce

**Comment by ssweber** [comment]
Great, I’ll test later!

**Comment by ssweber** [comment]
#126 I pushed a change that fixes this
