### ISSUE TITLE
Naming convention improvements and standardization

### ISSUE THREAD

**Issue by PySimpleSQL** [PySimpleSQL/pysimplesql#122]
The project has evolved pretty rapidly from a small personal project for my own needs, and has a lot of legacy stuff laying around, especially with variable names.

One that sticks out is ss.record() - originally this configured and an entire row; but has evolved and is now used to define record fields.
Another is the use of the word field vs column.  I want to work on standardizing some of these naming conventions.
When referring to a database:
use terms table, row, column

When referring to data from the database:
use terms query, record, field

**Comment by PySimpleSQL** [comment]
Sorry, it had to be done.  The code is much cleaner and more readable now.
There was a lot of ambiguity with table and query, some of which were completely wrong.

I did notice some bugs that I didn't have time to track down yet
- inserting a record, hitting previous to navigate away and choosing no to save moves the current index by 2
- Using quick editor, edit a foreign key value.  When the editor closes, update to the new value doesn't happen until a record change

**Comment by ssweber** [comment]
These are great changes. Looking forward to reading through again once you’re done.

Doing a quick search on Ms access… they call them fields / field controls. So you’re probably in the right ballpark.

**Comment by PySimpleSQL** [comment]
I wonder if instead of  naming the function for what it is: (field(),
element(), control()), I should be looking for a function name for what it
does:
bind(), relate(), unite(), associate(),  link(),  map(), attach()

**Comment by ssweber** [comment]
Some searches to see what others call it...

- [Appgini](https://bigprof.com/appgini/tips-and-tutorials/automatic-values-in-fields)
- [UDesigner - Adding Fields to a Form](https://docs.oracle.com/cd/E37673_01/English/User_Guides/uDesignerHelp/uDesigner/Content/uDesigner/18Designing%20a%20Form/Adding_Fields_to_a_Form.htm)
- [Designing Forms - Quickbase](https://helpv2.quickbase.com/hc/en-us/articles/4570300784788-Designing-forms-)

**Comment by ssweber** [comment]
I like DataSet. Especially with you’re new FlatPack - would never consider a csv file a query or a table :)

**Comment by PySimpleSQL** [comment]
There is one more thing on my list yet.  I'm not crazy about the naming
conventions of the drivers themselves- the user has to just know what they
are, and they aren't exactly easy to find for someone not familiar with the
source code.

I've been kicking around a few options:
- move the drivers to a separate file.  User could then do driver =
ss.drivers.Sqlite()..
I like that finding the drivers becomes easier and that an IDE could show
context as it's typed out,  but we would lose the single-file import
option.  In any case, it would be nice to come up with an elegant way to
define a driver in which IDEs would hint the options as the user types out
code.

- make an ss.drivers dict; driver = ss.drivers["SQLite"]()...

- make some type of master function as.driver("SQLite", path=...)

- make a class function in SQLDriver; driver
=ss.SQLDriver.driver("SQLite")...

- make a generic driver class with methods for each individual driver so
that an IDE could hint them

Most of these options would require manually adding some type of
key/variable/method that points to the actual driver class, which I'm not
really a huge fan of - every new driver would require some extra step and I
find it messy for an abstracted class to have some kind of knowledge about
other classes that extended it.  The driver.py file is probably the most
elegant option, but has the drawbacks I mentioned earlier - though I
honestly don't know how important having a single file import option is.

Any thoughts on this?

**Comment by PySimpleSQL** [comment]
PyCharm is amazing. You should give it a try.  Once you have it installed I
can share my workflow with you. I'm using the community edition now, but I
applied for two professional licenses (they provide them to open source
projects that meet certain requirements)

Things are still going to be kind of slow for me this week.  I have 80
hours scheduled to work at my normal job this week, at least 20 hours this
week running our Amazon business and some oddball meetings sprinkled in
there too.  I'm doing most everything from my phone right now
