### ISSUE TITLE
Optimization: Only update fk fields (eg combo dropdowns) associated with quick editor

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#123]
On the quick editor bug, we could quickly change the prompt save to a form level prompt save, then it would be safe to call update_elements().

A more nuanced approach would be to call update elements only on combo boxes that are associated with that foreign key

**Comment by PySimpleSQL** [comment]
I think this worked properly before though, at least within a couple of
days.  It be a simple renaming issue
