### ISSUE TITLE
Integrate set_label_size()`, `set_element_size()`, `set_mline_size() into themepack

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#156]
I saw you got rid of get/set ttk_theme

What do you think about add these to themepack and ditching their setters?

I ask, because overr time I plan to use themepack to store any popup setting enhancements (padding, msg font, button font) as well as sensible defaults for other widgets (I think slider is missing a default size?)

**Comment by PySimpleSQL** [comment]
ttk_theme is already a key in the themepack dict, so the setter/getter was no longer necessary

Good idea on the default sizes, those would be great in the themepack
