### ISSUE TITLE
Non-blocking info popup

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#170]
Current Popup.info is modal (blocking), in order to use a while-loop and close on auto-close event.

this has unfortunate effect of making saves seem slower than they are — update_events() is only called after popup close.

I looked at this when creating the Popup class, but wanted to get things converted quickly.

I think the solution is to create an invisible info popup on startup, and have the main loop update it’s contents, make it visible, and then start a timer that makes it invisible again.

Will investigate further after 3.0

**Comment by ssweber** [comment]
https://github.com/PySimpleGUI/PySimpleGUI/issues/5983

**Comment by ssweber** [comment]
I have a working version of this that I'll pull after current pull-requests merge

**Comment by ssweber** [comment]
https://user-images.githubusercontent.com/57631333/225638668-d73a765e-5b44-4c8f-8052-ea2f74196bf1.mp4

**Comment by PySimpleSQL** [comment]
Yeah, I like it!
