### ISSUE TITLE
MySQL example: CREATE TEMPORARY TABLES privilege

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#172]
I couldn’t test duplicate for MySQL, need CREATE TEMPORARY TABLES privilege. After creation, it doesn’t check privileges on temp tables (so you don’t need to enable drop)

**Comment by ssweber** [comment]
If it still balks at DROP (even though it says it doesn’t check permissions on dropping a temp table), then my second step was to skip drop, first try to create table, and if it exists, delete from, then insert. I could see users setting permission to allow Temporary Table Creation, but not Drop.

that’s why I changed the tmp table name to tmp_appendedtablename, so that during a session there could be multiple tmp tables open for duplicating.

**Comment by PySimpleSQL** [comment]
Fixed these permissions for MySQL

shoot me a private email when you get a chance; pysimplesql@gmail.com
I have HelioHost login credentials for you

**Comment by ssweber** [comment]
Emailed you
