### ISSUE TITLE
AttributeError: 'list' object has no attribute 'col_name' - PySimpleSQL for PostgreSQL

### ISSUE THREAD

**Issue by bmontana** [PySimpleSQL/pysimplesql#175]
I'm trying to learn PySimpleSQL. I started off with the first example in the Readme.md file (with modifications for my own database).  See the code below. I'm getting `AttributeError: 'list' object has no attribute 'col_name'`. So, I tried with the example code without mods. Same error. I also tried the `journal_postgres.py` example. Same error. Here is the stack trace from my file:

```
Traceback (most recent call last):
  File "/Users/bill/PycharmProjects/EZ DryClean/src/sql_practice/pss01.py", line 16, in <module>
    form = ss.Form(ss.Postgres('localhost', 'postgres', 'bmodevo', 'practice01'), bind=window)
  File "/Users/bill/PycharmProjects/EZ DryClean/src/sql_practice/pysimplesql.py", line 1440, in __init__
    self.auto_add_queries(prefix_queries)
  File "/Users/bill/PycharmProjects/EZ DryClean/src/sql_practice/pysimplesql.py", line 1640, in auto_add_queries
    description_column = column_info.col_name(1)
AttributeError: 'list' object has no attribute 'col_name'
```

I'm using PostgreSQL 15.1 and Python 3.9 on MacOS 12.6.3, and pysimplesql for PostgreSQL from GitHub. `pysimplesql.py` is installed in the same directory as my code files. My IDE is PyCharm Professional 2022.1.1.

I'm not sure if I'm doing something wrong, or if there is an issue with pysimplesql. Any ideas?

### pss01.py
```python
import psycopg2
import PySimpleGUI as sg
import pysimplesql as ss                               # <=== PySimpleSQL lines will be marked like this.  There's only a few!
import logging
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)               # <=== You can set the logging level here (NOTSET,DEBUG,INFO,WARNING,ERROR,CRITICAL)

layout = [
    [ss.record('customer.phone')],
    [ss.record('customer.lname'), ss.record('customer.fname')], 
    [ss.actions('act_customer', 'customer')]
]

window = sg.Window('Customers', layout, finalize=True)
form = ss.Form(ss.Postgres('localhost', 'postgres', 'password', 'practice01'), bind=window)

while True:
    event, values = window.read()

    if ss.process_events(event, values):  # <=== let PySimpleSQL process its own events! Simple!
        logger.info('PySimpleDB event handler handled the event!')
    elif event == sg.WIN_CLOSED or event == 'Exit':
        form = None  # <= ensures proper closing of the database and runs a database optimization at close
        break
    else:
        logger.info(f'This event ({event}) is not yet handled.')

window.close()
```

**Comment by ssweber** [comment]
Hi!
Which branch did you checkout to test? We are currently working in the [Development branch](https://github.com/PySimpleSQL/pysimplesql/tree/17377df2c6565c9630f9b042c8e812042282ad0a/pysimplesql). We are getting very close to a release, but unfortunately there are still some rough edges (see open pulls)

I’ll try to install Postgres locally so I can do some testing and try to replicate your issue, or provide a solution!

**Comment by PySimpleSQL** [comment]
Hello,

Please switch to the development branch.  The main branch documentation is
out of date, and the development  branch is so  close to release it's just
not worth the time updating, sorry!

The development branch will be pulled into the main branch pretty soon, and
there are some major changes, so working with the development branch would
be advised.

I've been out of town all week, but hopefully I can finish
some.cleanuonwhen I get back and get the development branch finished up and
pulled over.

**Comment by PySimpleSQL** [comment]
I just pushed a change that lets you try out the journal_postgres.py example.  Sorry, working from my phone and pretty limited on what I can do at the moment.  I'm supposed to finally get home tonight, so I should be able to help more when I get back

**Comment by bmontana** [comment]
The development branch works for me with the updated `journal_postgres.py` example. Thanks for your quick response on this. My code now works, such as it is.

I'm exploring the possibility of using PySimpleSQL with my students in my high school Computer Science classroom, and for personal projects. I'm just beginning to use PySimpleGUI<sup>TM</sup> in the classroom. PySimpleSQL would allow for more real-world applications.

**Comment by PySimpleSQL** [comment]
Absolutely.  Please leave your feedback on this project.  It started out as a personal little library that I used in my own projects and didn't realize until I had others ask me how I was able to develop some pretty complex database applications it occurred to me that others would benefit from it.  Then I was lucky enough to have @ssweber come along and help me start cleaning it up and making it more general purpose.  Feedback from someone who teaches these subjects could really help continue to guide this project in a good direction!

**Comment by PySimpleSQL** [comment]
Just pushed another Postgres fix.  Things should be getting more stable now for the driver.  I'll have a lot more free time coming up, so I'll definitely concentrate on this some more to make sure everything works smooth for you.  Please log any issues you have and I'll make sure we look into it

**Comment by ssweber** [comment]
@bmontana If you are still using PySimpleSql - take a look at the [WIP branch ](https://github.com/PySimpleSQL/pysimplesql/tree/wip) - Where all the current development is taking place.

I have a an example that shows off all the current functionality pretty well - see https://github.com/PySimpleSQL/pysimplesql/blob/wip/examples/orders_multiple_databases.py
