### ISSUE TITLE
**kwargs for actions() to allow use_ttk_buttons, padding, etc 

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#177]
Current buttons (with background colors hard-coded):
![current](https://user-images.githubusercontent.com/57631333/226020890-f34fe7df-9d78-4452-99a6-5e466dfb7a50.png)

I'd like to allow kwargs in actions(), and delete the hard-coded background colors. Without use_ttk_buttons, it doesn't look much different:
`[ss.actions("person", default=True)],`
![kwargs_with_no_ttk](https://user-images.githubusercontent.com/57631333/226021281-9c8143e6-4289-41ab-9c3c-61e3d32f711e.png)

But with use_ttk_buttons, you get nice highlight on select:
`[ss.actions("person", default=True, use_ttk_buttons = True, pad = (2,0))],`

https://user-images.githubusercontent.com/57631333/226021466-1da373ec-f2e9-41b8-ae1e-7133bb9ed0c1.mp4

**Comment by ssweber** [comment]
Or let me know if you think we should put it in themepack:

actions_use_ttk_buttons = True/False
actions_pad =

**Comment by PySimpleSQL** [comment]
Yeah, this is a good idea.  It's definitely best to get rid of the hard coding.  If someone wants a background color, they could include it in the image for the button.

**Comment by ssweber** [comment]
#181
