### ISSUE TITLE
Rename “recursive” to “cascade” in codebase

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#184]
I’ve introduced a bunch of “recursive language, now that I’m more familiar with the code base, I’d like to rename all those “cascade” before release.

**Comment by ssweber** [comment]
see #191

**Comment by PySimpleSQL** [comment]
Yeah, this makes a lot of sense.  It didn't matter so much early on, but now there is a lot of different cascading options it would be nice to dial in the naming convention

**Comment by ssweber** [comment]
#194

**Comment by ssweber** [comment]
I think I’ll just change the records_changed recursive parameter to cascade, and then close this for now.

That only leaves the actual functions named recursive.

**Comment by ssweber** [comment]
Nvm. I decided to leave as is, and we can keep it that way unless a better naming scheme is proposed.
