### ISSUE TITLE
Change project description for PyPi 

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#193]
Getting excited about wrapping things up for 3.0!

Currently set to “ SQLite3 binding for PySimpleGUI”

Let’s brainstorm a new good description!

**Comment by PySimpleSQL** [comment]
Yeah, it definitely has changed since then.  I'll put this on my list for tomorrow as well

**Comment by ssweber** [comment]
Here’s a stab at it (may still be too long?):

pysimplesql - Rapid database-driven application development for PySimpleGUI. Supports SQLite, MySQL, MariaDB, PostgreSQL, and Flatfile CSV. Create user interfaces with automatic relationship handling, dynamic comboboxes, sortable tables, “required” fields, customizable button themes and localization. Built-in edit protect and data-loss prevention. Advanced functionality includes data transforms, callbacks, event-mapping, and other low-level functions.

**Comment by ssweber** [comment]
Rapid database-driven application development for PySimpleGUI. Supports SQLite, MySQL/MariaDB, PostgreSQL, and Flatfile CSV. Lightweight, low-code library with advanced customization and direct SQL access.

**Comment by ssweber** [comment]
Here’s another: 

Write data-connected desktop apps fast! Lightweight Python library supports SQLite, MySQL/MariaDB, PostgreSQL & Flatfile CSV w/ PySimpleGUI layouts.

**Comment by ssweber** [comment]
I like the above a lot, because

1. It says what kind of apps you use it for
2. Tells you it’s lightweight (not a huge dependency to learn and manage)
3. Which databases it supports
4. And that you use PySimpleGUI layouts.

**Comment by ssweber** [comment]
Again, just playing around with this. Yours to take or leave!

**Comment by PySimpleSQL** [comment]
Yeah, I like it.  I'm excited to get on this vacation and get some time to clean up stuff like this

**Comment by PySimpleSQL** [comment]
I think it's time for a graphical icon or logo as well

**Comment by ssweber** [comment]
Yeah started thinking about a logo too… keep banging around how to convey what it’s all about
