### ISSUE TITLE
Contact info?

### ISSUE THREAD

**Issue by PySimpleGUI** [PySimpleSQL/PySimpleSQL#2]
Hi there.... I was looking at your account to see if there's an email address associated with it, but I don't see one.  Can you drop me an email at PySimpleGUI at PySimpleGUI dot com?

**Comment by PySimpleSQL** [comment]
Sorry for the hiatus.  I've had some more important issues to deal with this year - but finally have things under control so that I can pick back up.

I'll send you an email soon!
