### ISSUE TITLE
Branch protection rules

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#230]
Thanks for adding me. I’ve never contributed to a library before, and have always wanted an easy, low dependency rad tool. It’s been a good learning experience.

See [GitHub doc on requiring pulls and approvals](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule) 

I’m fine if you do pull requests, or if it remains easier, to keep to pushing into development. 

I don’t get on social media, and am fine to keep communicating via GitHub issues.

**Comment by ssweber** [comment]
Looks like you've figured it out. But wanted to show my super basic workflow with GitHub Desktop.

I create a new branch based on development for each new feature I want to make a pull-request for.
If I forget, I can still switch to development, create a new branch and pull over my un-commited changes to the new branch.

After publishing the branch, creating the pull-request, (and before the pull-request is merged), I can add new commits to the branch, 'push origin', and they show up on the pull-request.

https://user-images.githubusercontent.com/57631333/228933594-e750697d-6480-4740-8132-968ef79e39a8.mp4

**Comment by ssweber** [comment]
Example if I make changes to a new feature, but forget that I'm in the 1st feature branch. I've learned it takes a little discipline not to edit the same areas, to avoid merge conflicts.


https://user-images.githubusercontent.com/57631333/228937117-bd33d7d3-1b4c-46ac-8544-34a4f8916c8e.mp4

**Comment by PySimpleSQL** [comment]
Thanks, I appreciate you sharing your workflow with me.  As I've said
before, Git and collaboration are pretty new to me.  This should definitely
help me learn more about the entire process.  I'll do my best to keep
mistakes to a minimum as I go through the process and learn more.

**Comment by PySimpleSQL** [comment]
Well welcome aboard.  In my opinion, you have earned an equal say in
direction of the project.  I may look at at a system to make this a little
more democratic moving forward (https://github.com/cncf/gitvote,
https://github.com/marketplace/actions/git-democracy, etc).  I'm sure as
the project matures, pull requests could become more common, and more
contributors could get involved.  In any case, even with just two people it
makes for a nice system of checks and balances to keep the project on track.

For now though, I'll stick to the plan of doing pull requests.  At minimum
we can both raise questions or concerns before a change goes into the
codebase.

**Comment by ssweber** [comment]
Don’t underestimate the benefit of a benevolent ruler! You’ve certainly have helped keep most of my bad ideas out.

For your pull requests, do you want me to approve and merge, or just approve… leaving you to merge?

I’m fine either way.

**Comment by PySimpleSQL** [comment]
You can approve and merge if that's fine by you.

I think the benevolent rule that was needed early on is no longer
required.  It's been a learning process, and I've learned that letting go
of that kind of control has lead the project in a better direction.

Im too inexperienced with too many things to want everything on my
shoulders anyway.  I'd rather continue learning new things and different
sides of the things that I do know.

**Comment by PySimpleSQL** [comment]
Branch protection rules are now in place for development and master. Le me know if you think anything needs changed
