### ISSUE TITLE
How to deal with serialized arrays

### ISSUE THREAD

**Issue by Tsjippy** [PySimpleSQL/pysimplesql#25]
How can I work with sql data that needs some work before displaying? For instance unserializing a serialized array from the db

**Comment by GitHubJohn2** [comment]
Trying to answer this without knowing the essence of the data and its structure could make a guy's head explode.  It is flat or nested? Is it a single type?   Can you pull it into a one dimensional unitary type data vector  (no n dimensional support)?  If so the Python Array module could be your answer.  Good luck.

**Comment by Tsjippy** [comment]
sorry I should give more details here it comes.

I am building a very simple library package.

I have 3 tables: users, items and settings.

Each user in the user table can borrow a maximum number of items as defined in the settings table.

How can I display which books a user has borrowed, and how many he still can borrow?

On the settings tab people should be able to enter which item types are available in the library, books, DVD's etc. So I suppose that should be stored as an array and show as a field.

this is my db structure but I can change that:
```
DROP TABLE IF EXISTS "Users";
DROP TABLE IF EXISTS "Items";
DROP TABLE IF EXISTS "Settings";

CREATE TABLE "Users"(
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"firstname" TEXT DEFAULT "New User",
	"lastname" TEXT DEFAULT "New User",
	"barcode" INTEGER,
	"profile_picture" INTEGER,
	"items" TEXT
);

CREATE TABLE "Items"(
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"title" TEXT DEFAULT "New Type"
	"author" TEXT DEFAULT "New Type"
	"isbn" INTEGER,
	"cover_picture" INTEGER,
	"barcode" INTEGER,
);

CREATE TABLE "Settings"(
	"pkMenu" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"itemtypes" TEXT DEFAULT "New Menu",
	"maxitems" INTEGER,
);

INSERT INTO "Items" VALUES (1,"Bible", "Moses", 1234567890, 1, 3);

INSERT INTO "Settings" VALUES (1,"{a:2{s:4:book;s3:DVD}}" , 5);

INSERT INTO "Users" VALUES (1,"Ewald", "Harmsen", 2, 34,"{}");
```
