### ISSUE TITLE
docstring style for mkdocstrings

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#251]
I'm planning on using mkdocs / mkdocstrings. Once we have them ready, we can easily host via github pages.

In order to get mkdocstrings working correctly, I'll need to do some docstring reformatting (last time I promise). Our sphinx-style are missing :type, so this is a good time to reformat.

We have [three options of docstring styles](https://mkdocstrings.github.io/python/usage/#supported-docstrings-styles):

I personally prefer either the google or numpy style. They read alot better in the code. [See here](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html)

Once that is done, the generated site will look like:

![image](https://user-images.githubusercontent.com/57631333/230178169-f2e6eb3f-6b84-49c0-b70b-0c4fc547c630.png)

**Comment by ssweber** [comment]
Looks like it also grabs type information from the function, so this:

![image](https://user-images.githubusercontent.com/57631333/230182972-4872a221-ef69-43a3-819d-81cc7b6294b2.png)

is generated without having to duplicate our types:

![image](https://user-images.githubusercontent.com/57631333/230183043-636da870-14b0-48c1-850b-ab1859e205fb.png)

**Comment by ssweber** [comment]
NVM! I didn't have the mkdocs config correct. Got it working with sphinx style. And we don't need the :type to get them working.

**Comment by PySimpleSQL** [comment]
Yeah, I thought the :type was optional.

I think the doc strings are looking pretty decent finally. What are your
thoughts on the formatting now?

**Comment by ssweber** [comment]
I think they look great. 

I was just confused initially, learning about how to do mkdocs and mkdocstrings to host.
