### ISSUE TITLE
Column_info improvements

### ISSUE THREAD

**Issue by PySimpleSQL** [PySimpleSQL/pysimplesql#259]
The Column_info class should be extended to capture secondary datatype/domain values.  For example, VARCHAR may be accompanied by a length, a DATE may be accompanied by a format.

This extra info can help when casting these values so that they show up as expected

since we call the datatype domain, i may call this extra information domain_ext

**Comment by ssweber** [comment]
I’ll try to integrate this into the domain classes I’m going to implement to handle.

**Comment by ssweber** [comment]
I’ve started converting Column to specialized columns that each have their own validate and cast function - https://github.com/PySimpleSQL/pysimplesql/tree/extended-column-classes . Havnt finalized the list of specialized columns or their naming.

I’m capturing the “255” in varcar(255) in “domain_args”, which we use to initialize StrCol(*domain_args, rest of Column kwargs here).

or for instance Decimal(4,2), the 4,2 gets passed to DecimalCol(precision,scale, kwargs)

etc. Also will play around with a Enum version that automatically would create a drop-down list for selection in a Table.

**Comment by ssweber** [comment]
Still have SqlServer, and MSaccess to go converting.

I've added a 'validate' function to each Column subclass. That plus a '_shake_animation' and you get this effect (will continue working on it so it's not too annoying). Biggest feature is it doesnt write a change unless it can be cast correctly:

https://github.com/PySimpleSQL/pysimplesql/assets/57631333/bec8d1b6-11f3-429a-9716-c3927c17b82c

**Comment by ssweber** [comment]
Only msaccess to go. I also fixed shake if date is only a partial date. Going through and refactoring and making it a general-purposed.

**Comment by ssweber** [comment]
I’m very close to finishing assigning column classes for msaccess. I’ve created a “test_all_column_domains” so we can make sure to capture all the different types.

I’m don’t think “decimal_digits” column is actually reporting the decimal positions as defined in access though, so may run into a little hiccup there. Will find out. I’m out for a few days on a trip.

**Comment by ssweber** [comment]
I might need to do some jackcess calls to get precision/scale. Will find out.

see https://jackcess.sourceforge.io/apidocs/com/healthmarketscience/jackcess/Column.html for what’s available.

**Comment by ssweber** [comment]
Almost finished this for msaccess. I think jackcess don’t actually get decimal_digits, precision or scale for more recent version.it’s always 0.

 I’m going to make an older version mdb and see if it’ll get them then.

**Comment by ssweber** [comment]
#338
