### ISSUE TITLE
Google-style docstrings

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#267]
This is not a 'must', and let me know if me bringing this up is annoying!

but I want your opinion, because I figured out how converting from current sphinx style to google-style would be fairly easy.

Currently our docs look like:

```
class ProgressBar:
    def __init__(self, title: str, max_value: int = 100, hide_delay: int = 100):
        """
        Creates a progress bar window with a message label and a progress bar.

        The progress bar is updated by calling the `update` method to update the
        progress in incremental steps until the `close` method is called.

        :param title: Title of the window
        :param max_value: Maximum value of the progress bar
        :param hide_delay: Delay in milliseconds before displaying the Window
        :returns: None
        """
```
Google-style:
```
class ProgressBar:
    def __init__(self, title: str, max_value: int = 100, hide_delay: int = 100):
        """Creates a progress bar window with a message label and a progress bar.

        The progress bar is updated by calling the `update` method to update the
        progress in incremental steps until the `close` method is called.

        Args:
            title: Title of the window
            max_value: Maximum value of the progress bar
            hide_delay: Delay in milliseconds before displaying the Window

        Returns:
            None
        """
```
The reason I'm bringing this up, is switching would allow us to easily add `admonitions` that get formatted by mkdocstrings:

![image](https://user-images.githubusercontent.com/57631333/230663532-82fde6f5-c103-4836-b435-e87c3464f8ed.png)
![image](https://user-images.githubusercontent.com/57631333/230663553-131c96bd-90d7-4c79-a5c6-5db49c0e6e3e.png)

As a plus, alot of the param lines we currently have to wrap to fit under 88 could all fit on 1 line instead.

**Comment by ssweber** [comment]
Honestly, I should probably just leave them be and focus on the Readme, and generating useful docs/sections.

Things like this are just easy mindless revision... so its appealing when I'm procrastinating on something else.

**Comment by PySimpleSQL** [comment]
I'm fine with the google-styke doc strings.  I can definitely see some
advantages

**Comment by ssweber** [comment]
I’m waiting to see if docformatter will implement parameter wrapping in the near-term (it’s next on the issue tracker).

then this will be an easy [docconvert](https://github.com/cbillingham/docconvert/blob/main/doc/source/index.rst) , docformatter, minor fixes.

**Comment by ssweber** [comment]
Added this to WIP branch.
