### ISSUE TITLE
GitHub Pages test

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#283]
I just built the test mkdocs/mkdocstrings to the branch gh-pages. (cd into root folder, and run `mkdocs gh-deploy --no-history`)

I don't have access to settings to try out GitHub pages. Could you do the following (setting it to build from gh-pages branch)? I believe you'll leave it at root.

![image](https://user-images.githubusercontent.com/57631333/231867836-ef579ad7-009f-4b9b-8f16-9f79e96f0656.png)

**Comment by ssweber** [comment]
(if you're good with eg pysimplesql.github.io as the docs site)

From the github/pypi readme, we would then put hard-coded links to the pysimplesql.github.io pages.

For example, see how ttkbootstrap layed out it's [Readme.md](https://pypi.org/project/ttkbootstrap/), and [then documentation site](https://ttkbootstrap.readthedocs.io/en/latest/). 

Or [Ruff pypi](https://pypi.org/project/ruff/), [docs site](https://beta.ruff.rs/docs/)

**Comment by PySimpleSQL** [comment]
Whatever you think is fine with me.  You seem to have a lot more experience
than me with documentation (aside from general  inline comments, it's
something I've been lacking in for a while).

**Comment by ssweber** [comment]
Thanks for your vote of confidence 😝 

I don't have the clearance level to activate pages. Could you do that for us? No rush, just thought maybe you missed that in my original post.

Here's how you get there:

https://user-images.githubusercontent.com/57631333/232080483-691e071f-0f2d-49b0-8758-987024b0dc57.mp4

**Comment by PySimpleSQL** [comment]
Sorry I just got around to this, I haven't been at a computer.  Gh-pages
branch should be active now

**Comment by ssweber** [comment]
Thanks!

https://pysimplesql.github.io/pysimplesql/
