### ISSUE TITLE
Shillelagh sqldriver

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#286]
I just found this, and it looks like a really cool fit for a sqldriver: https://github.com/betodealmeida/shillelagh/

I think it uses SQLite under the hood, but look at all the connection possibilities!

**Comment by PySimpleSQL** [comment]
I'll add it to the list.  DuckDb is another one that I'm wanting to add as
well.

I have some early work done on transitioning to Pandas,. It's almost fully
working already.

On the road for most of today, but I'll be pushing updates as I get the
opportunity throughout the day

**Comment by ssweber** [comment]
I was wondering if you were pandizing 😄

**Comment by ssweber** [comment]
Closing this for now. More interested in polishing what we have.
