### ISSUE TITLE
Handling our own click events

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#289]
We need a good solution to “lost changes because user navigated to new record on virtual record save exception” 

This is relatively easy to prevent when an action button is used for the navigation change. But on selectors, we are reacting to a gui-change that’s already happened.

It came to me last night: why don’t we bind click events, and setup a handler to catch selector rows? For sg.Tables we would set `select=sg.TABLE_SELECT_MODE_NONE`, capture row clicks, and only select_row when the changes have safely saved.

I’ll have to take a look at how the logic works for sg.Slider, but Listbox/Combobox should be similar.

**Comment by ssweber** [comment]
Here’s the related code for that (quickly modifying from my editable table testing:

```
window.TKroot.bind("<Button-1>", callback)

def callback(event):
    # if click a treeview
    if event.widget.__class__.__name__ == 'Treeview':
        tk_widget = event.widget
        
        # identify region
        region = tk_widget.identify('region', event.x, event.y)

        if region == 'cell':
            # get row and column
            row = int(tk_widget.identify_row(event.y))
            col_identified= tk_widget.identify_column(event.x)
            if col_identified:
                column = int(tk_widget.identify_column(event.x)[1:])-1
        else:
            return

        for data_key in [data_key for data_key in frm.datasets if len(frm[data_key].selector)]:
            for e in frm[data_key].selector:
                element = e['element']
                if element.widget == tk_widget:
                    print(data_key)

**Comment by PySimpleSQL** [comment]
Thanks, I wi check things out ASAP.  Off to a pretty bad start at work
today so I've been tied up

**Comment by ssweber** [comment]
Becoming less reliant on the PySimpleGui event-loop has another benefit to this: we could generalize pysimplesql to be used in normal tkinter or [ttkbootstrap](https://github.com/israel-dryer/ttkbootstrap/issues).

**Comment by ssweber** [comment]
Looking at this further, Listbox, Combobox, Slider don’t have a sg.TABLE_SELECT_MODE_NONE, so probably we would only call set_by_index after a successful (saved/discarded) prompt_save call… otherwise call whatever tk call there is to select the previously selected index

**Comment by ssweber** [comment]
I’m going to see what it looks like just by adding a PROMPT_SAVE_FAIL, and call update_selectors(self.table) in the prompt_save() routine.

**Comment by ssweber** [comment]
#298 Fixes what was motivating this. I think it would be interesting to provide a single-click bind-function that replaces the need for ss.process_events - but it's not necessary.
