### ISSUE TITLE
How to override default order

### ISSUE THREAD

**Issue by ffaffer** [PySimpleSQL/pysimplesql#29]
I'm having difficulty in changing the initial order from the default second field of a pre-existing database. Can you show me how this can be done and how I can add a WHERE clause.

**Comment by PySimpleSQL** [comment]
Hello

Check out:
set_description_column() for setting which column is used in comboboxes, etc 

set_where_clause() will allow you to manually set the where clause, though in most cases you shouldn't need to do this manually.

Can you share what you're trying to do and I'll do my best to point you in the right direction

**Comment by ffaffer** [comment]
Hi
Thanks for the quick response.
I've attached my script, which is intended to aid maintaining a hobby database.  The script was simple to write and works very well except I would like the default order to be based on the 'ID' column.
Your guidance will be appreciated.
  
Kind Regards

======
import PySimpleGUI as sg
import pysimplesql as ss                              # <=== PySimpleSQL lines will be marked like this.  There's only a few!
import logging

from pysimplesql import Form

logger=logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)               # <=== You can set the logging level here (NOTSET,DEBUG,INFO,WARNING,ERROR,CRITICAL)
# -------------------------
# CREATE PYSIMPLEGUI LAYOUT
# -------------------------
# Define the columns for the table selector
columns=['ID','Make','Model']
headings=['ID ','Make:    ','Model:     ']
visible=[1,1,1]
layout=[
    [ss.selector("sel","pens",sg.Table, headings=headings,visible_column_map=visible, columns=columns,num_rows=10)],
    [ss.record('pens.ID', s=15,  label='ID')], 
    [ss.record('pens.Make',s=15,  label='Make')],
    [ss.record('pens.Model',s=15,  label='Model')],
    [ss.record('pens.MfgYear',s=15,  label='MfgYear')],
    [ss.record('pens.barrel' ,s=15,  label='Barrel')],
    [ss.record('pens.Nib',s=15 , label='Nib')],
    [ss.record('pens.Filler',s=15,  label='Filler')],
    [ss.record('pens.Material',s=15,  label='Material')],
    [ss.record('pens.Cap',s=15,  label='Cap')],
    [ss.record('pens.inked',s=15,  label='inked')],
    [ss.record('pens.Comments',s=15,  label='Comments')],
    [ss.record('pens.Marks',s=15, label='Marks')],
    [ss.record('pens.Refurb',s=15,  label='Refurb')],
    [ss.record('pens.RefurbCost',s=15,  label='RefurbCost')],
    [ss.record('pens.RefurbDate',s=15,  label='RefurbDate')],
    [ss.record('pens.Purch',s=15,  label='Purch')],
    [ss.record('pens.Cost',s=15,  label='Cost')],
    [ss.record('pens.Source',s=15,  label='Source')],
    [ss.record('pens.Sale',s=15,  label='Sale')],  
    [ss.record('pens.SaleDate',s=15,  label='SalesDate')],
    [ss.record('pens.Pics',s=15,  label='Pics')],
    [ss.actions("browser","pens", search=False)]
]

win=sg.Window('Pens', layout, font = fnt, finalize=True)
# Create our frm
frm=ss.Form('/home/ken/sspens.db', bind=win)


# ---------
# MAIN LOOP
# ---------
while True:
    event, values = win.read()

    if ss.process_events(event, values):                  # <=== let PySimpleSQL process its own events! Simple!
        logger.info(f'PySimpleDB event handler handled the event {event}!')
    elif event == sg.WIN_CLOSED or event == 'Exit':
        frm=None              # <= ensures proper closing of the sqlite database and runs a database optimization
        break
    else:
        logger.info(f'This event ({event}) is not yet handled.')

**Comment by GitHubJohn2** [comment]
Through I admire the program, I do not support PySimpleSQL.Good Luck!John
    On Thursday, October 20, 2022 at 06:58:38 AM EDT, ffaffer ***@***.***> wrote:  
 
 


Hi
Thanks for the quick response.
I've attached my script, which is intended to aid maintaining a hobby database. The script was simple to write and works very well except I would like the default order to be based on the 'ID' column.
Your guidance will be appreciated.

Kind Regards

======
import PySimpleGUI as sg
import pysimplesql as ss # <=== PySimpleSQL lines will be marked like this. There's only a few!
import logging

from pysimplesql import Form

logger=logging.getLogger(name)
logging.basicConfig(level=logging.INFO) # <=== You can set the logging level here (NOTSET,DEBUG,INFO,WARNING,ERROR,CRITICAL)

-------------------------

CREATE PYSIMPLEGUI LAYOUT

-------------------------

Define the columns for the table selector

columns=['ID','Make','Model']
headings=['ID ','Make: ','Model: ']
visible=[1,1,1]
layout=[
[ss.selector("sel","pens",sg.Table, headings=headings,visible_column_map=visible, columns=columns,num_rows=10)],
[ss.record('pens.ID', s=15, label='ID')],
[ss.record('pens.Make',s=15, label='Make')],
[ss.record('pens.Model',s=15, label='Model')],
[ss.record('pens.MfgYear',s=15, label='MfgYear')],
[ss.record('pens.barrel' ,s=15, label='Barrel')],
[ss.record('pens.Nib',s=15 , label='Nib')],
[ss.record('pens.Filler',s=15, label='Filler')],
[ss.record('pens.Material',s=15, label='Material')],
[ss.record('pens.Cap',s=15, label='Cap')],
[ss.record('pens.inked',s=15, label='inked')],
[ss.record('pens.Comments',s=15, label='Comments')],
[ss.record('pens.Marks',s=15, label='Marks')],
[ss.record('pens.Refurb',s=15, label='Refurb')],
[ss.record('pens.RefurbCost',s=15, label='RefurbCost')],
[ss.record('pens.RefurbDate',s=15, label='RefurbDate')],
[ss.record('pens.Purch',s=15, label='Purch')],
[ss.record('pens.Cost',s=15, label='Cost')],
[ss.record('pens.Source',s=15, label='Source')],
[ss.record('pens.Sale',s=15, label='Sale')],
[ss.record('pens.SaleDate',s=15, label='SalesDate')],
[ss.record('pens.Pics',s=15, label='Pics')],
[ss.actions("browser","pens", search=False)]
]

win=sg.Window('Pens', layout, font = fnt, finalize=True)

Create our frm

frm=ss.Form('/home/ken/sspens.db', bind=win)

---------

MAIN LOOP

---------

while True:
event, values = win.read()
if ss.process_events(event, values):                  # <=== let PySimpleSQL process its own events! Simple!
    logger.info(f'PySimpleDB event handler handled the event {event}!')
elif event == sg.WIN_CLOSED or event == 'Exit':
    frm=None              # <= ensures proper closing of the sqlite database and runs a database optimization
    break
else:
    logger.info(f'This event ({event}) is not yet handled.')

**Comment by PySimpleSQL** [comment]
> Hi Thanks for the quick response. I've attached my script, which is intended to aid maintaining a hobby database. The script was simple to write and works very well except I would like the default order to be based on the 'ID' column. Your guidance will be appreciated.
> 
> Kind Regards
> 
> ====== import PySimpleGUI as sg import pysimplesql as ss # <=== PySimpleSQL lines will be marked like this. There's only a few! import logging
> 
> from pysimplesql import Form
> 
> logger=logging.getLogger(**name**) logging.basicConfig(level=logging.INFO) # <=== You can set the logging level here (NOTSET,DEBUG,INFO,WARNING,ERROR,CRITICAL)
> 
> # -------------------------
> # CREATE PYSIMPLEGUI LAYOUT
> # -------------------------
> # Define the columns for the table selector
> columns=['ID','Make','Model'] headings=['ID ','Make: ','Model: '] visible=[1,1,1] layout=[ [ss.selector("sel","pens",sg.Table, headings=headings,visible_column_map=visible, columns=columns,num_rows=10)], [ss.record('pens.ID', s=15, label='ID')], [ss.record('pens.Make',s=15, label='Make')], [ss.record('pens.Model',s=15, label='Model')], [ss.record('pens.MfgYear',s=15, label='MfgYear')], [ss.record('pens.barrel' ,s=15, label='Barrel')], [ss.record('pens.Nib',s=15 , label='Nib')], [ss.record('pens.Filler',s=15, label='Filler')], [ss.record('pens.Material',s=15, label='Material')], [ss.record('pens.Cap',s=15, label='Cap')], [ss.record('pens.inked',s=15, label='inked')], [ss.record('pens.Comments',s=15, label='Comments')], [ss.record('pens.Marks',s=15, label='Marks')], [ss.record('pens.Refurb',s=15, label='Refurb')], [ss.record('pens.RefurbCost',s=15, label='RefurbCost')], [ss.record('pens.RefurbDate',s=15, label='RefurbDate')], [ss.record('pens.Purch',s=15, label='Purch')], [ss.record('pens.Cost',s=15, label='Cost')], [ss.record('pens.Source',s=15, label='Source')], [ss.record('pens.Sale',s=15, label='Sale')], [ss.record('pens.SaleDate',s=15, label='SalesDate')], [ss.record('pens.Pics',s=15, label='Pics')], [ss.actions("browser","pens", search=False)] ]
> 
> win=sg.Window('Pens', layout, font = fnt, finalize=True)
> 
> # Create our frm
> frm=ss.Form('/home/ken/sspens.db', bind=win)
> 
> # ---------
> # MAIN LOOP
> # ---------
> while True: event, values = win.read()
> 
> ```
> if ss.process_events(event, values):                  # <=== let PySimpleSQL process its own events! Simple!
>     logger.info(f'PySimpleDB event handler handled the event {event}!')
> elif event == sg.WIN_CLOSED or event == 'Exit':
>     frm=None              # <= ensures proper closing of the sqlite database and runs a database optimization
>     break
> else:
>     logger.info(f'This event ({event}) is not yet handled.')
> ```

Hello,

Ok, I see what you want now I think.

Try adding the following just after your form creation:

```
frm['pens'].set_order_clause("ORDER BY ID ASC")
```

Let me know how it works out - sounds like a fun project :)

**Comment by ffaffer** [comment]
HiThanks again for the quick response.The suggested line makes no difference.  The sort order remains 'Make'.I've tried your earlier suggestion with the line frm['pens'].set_description_column('ID') with similar result.
A snippet of the Debug follows:DEBUG:pysimplesql.pysimplesql:Key generated: browser.table_delete
INFO:pysimplesql.pysimplesql:Importing database: /home/ken/sspens.db
INFO:pysimplesql.pysimplesql:Automatically generating queries for each table in the sqlite database...
DEBUG:pysimplesql.pysimplesql:Adding query "pens" on table pens to Form with primary key ID and description of Make
INFO:pysimplesql.pysimplesql:Requerying all queries...
INFO:pysimplesql.pysimplesql:Running query: SELECT * FROM pens    ORDER BY Make COLLATE NOCASE ASC
INFO:pysimplesql.pysimplesql:Bnding Window to Form...
Whatever I try seems to make no difference.
Thanks for your help
Kind Regards
    On Thursday, 20 October 2022 at 18:53:30 BST, PySimpleSQL ***@***.***> wrote:  
 
 



Hi Thanks for the quick response. I've attached my script, which is intended to aid maintaining a hobby database. The script was simple to write and works very well except I would like the default order to be based on the 'ID' column. Your guidance will be appreciated.

Kind Regards

====== import PySimpleGUI as sg import pysimplesql as ss # <=== PySimpleSQL lines will be marked like this. There's only a few! import logging

from pysimplesql import Form

logger=logging.getLogger(name) logging.basicConfig(level=logging.INFO) # <=== You can set the logging level here (NOTSET,DEBUG,INFO,WARNING,ERROR,CRITICAL)

-------------------------

CREATE PYSIMPLEGUI LAYOUT

-------------------------

Define the columns for the table selector

columns=['ID','Make','Model'] headings=['ID ','Make: ','Model: '] visible=[1,1,1] layout=[ [ss.selector("sel","pens",sg.Table, headings=headings,visible_column_map=visible, columns=columns,num_rows=10)], [ss.record('pens.ID', s=15, label='ID')], [ss.record('pens.Make',s=15, label='Make')], [ss.record('pens.Model',s=15, label='Model')], [ss.record('pens.MfgYear',s=15, label='MfgYear')], [ss.record('pens.barrel' ,s=15, label='Barrel')], [ss.record('pens.Nib',s=15 , label='Nib')], [ss.record('pens.Filler',s=15, label='Filler')], [ss.record('pens.Material',s=15, label='Material')], [ss.record('pens.Cap',s=15, label='Cap')], [ss.record('pens.inked',s=15, label='inked')], [ss.record('pens.Comments',s=15, label='Comments')], [ss.record('pens.Marks',s=15, label='Marks')], [ss.record('pens.Refurb',s=15, label='Refurb')], [ss.record('pens.RefurbCost',s=15, label='RefurbCost')], [ss.record('pens.RefurbDate',s=15, label='RefurbDate')], [ss.record('pens.Purch',s=15, label='Purch')], [ss.record('pens.Cost',s=15, label='Cost')], [ss.record('pens.Source',s=15, label='Source')], [ss.record('pens.Sale',s=15, label='Sale')], [ss.record('pens.SaleDate',s=15, label='SalesDate')], [ss.record('pens.Pics',s=15, label='Pics')], [ss.actions("browser","pens", search=False)] ]

win=sg.Window('Pens', layout, font = fnt, finalize=True)

Create our frm

frm=ss.Form('/home/ken/sspens.db', bind=win)

---------

MAIN LOOP

---------

while True: event, values = win.read()
if ss.process_events(event, values):                  # <=== let PySimpleSQL process its own events! Simple!
    logger.info(f'PySimpleDB event handler handled the event {event}!')
elif event == sg.WIN_CLOSED or event == 'Exit':
    frm=None              # <= ensures proper closing of the sqlite database and runs a database optimization
    break
else:
    logger.info(f'This event ({event}) is not yet handled.')


Hello,

Ok, I see what you want now I think.

Try adding the following just after your form creation:
frm['pens'].set_order_clause("ORDER BY ID ASC")

Let me know how it works out - sounds like a fun project :)

**Comment by PySimpleSQL** [comment]
Thanks for the additional info.  The debug info helps a lot

Actually, both methods that we tried above should have worked.  I think in hindsight, you need requery the database after either setting the description column or manually setting the order clause.  Hopefully this missing piece will get your desired result
```
frm['pens'].set_order_clause("ORDER BY ID ASC")  # or frm['pens'].set_description_column('ID')
frm['pens'].requery()
```

**Comment by ffaffer** [comment]
Thanks for your help.  That's done the trick.
For your info.  the set_order_clause works but the set_description_column don't.
Thanks again for your help and for making the library available.  Its been a huge help to a non-coder like me.
I'll close the issue now.
Kind regards
