### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by tcicit** [PySimpleSQL/PySimpleSQL#3]
Hello, pysimplesql is exactly what I was looking for :-).  A simple GUI for a small database. 
Unfortunately I get the following error when running your sample program. 

Traceback (most recent call last):
  File "example2.py", line 25, in <module>
    db = ss.Database('example2.db', win)      # <=== load the database and bind it to the window
  File "/home/test-db/pysimplesql.py", line 694, in __init__
    new_database = not os.path.isfile(sqlite3_database)
  File "/usr/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not Window
Exception ignored in: <function Database.__del__ at 0x7fd34ee2dca0>
Traceback (most recent call last):
  File "/home/test-db/pysimplesql.py", line 725, in __del__
    if self.path!=':memory:':
AttributeError: 'Database' object has no attribute 'path'

**Comment by Sprucelass** [comment]
Having this same issue.

**Comment by jrwhit1** [comment]
I've seen that error. This is the one I usually get.

Traceback (most recent call last):
  File "C:\Users\Joe\Documents\PythonCode\PySimpleGui\MakeSQLiteDB.py", line 18, in <module>
    ss.record_actions('Item', False)
AttributeError: module 'pysimplesql' has no attribute 'record_actions'

**Comment by dani-91** [comment]
Hi, I'm also currently testing the library. I solved the issue changing following line in pysimplesql.py (line 694):
            new_database = not os.path.isfile(sqlite3_database)
TO:
            new_database = not os.path.isfile(db_path)

and in example2.py (line 25):
db = ss.Database('example2.db', win, sql_file='example2.sql')
TO:
db = ss.Database('example2.db', win=win, sql_file='example2.sql')

**Comment by jrwhit1** [comment]
Good job, dani-91. I hadn't given up hope that someone would come up with the solution.

**Comment by PySimpleSQL** [comment]
Sorry for the hiatus 

Examples have been fixed!
Next step is getting this onto PyPi officially
