### ISSUE TITLE
Current WIP

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#312]
Little update… made huge progress yesterday and today getting functionality just right for a new “Orders” example that I’m going to record the opening readme with. 

It highlights most everything that makes pysimplesql so special… the automatic binding, relationship handling, prompt-saving, table sorting, with all the new live-updating functionality.

I’ll try to finish and create a pull for the following tomorrow:

* add the Orders example
* Add datepicker for celledit if domain is “date” - almost done, but want to include a version that doesn’t rely on GPL tkcalendar library
* Rewritten search function, that fills in descriptions if rel.fk
* Add write_event to set_current - so in Main Loop you can have custom code that acts on cell/liveupdates
* add SQLite generated column handling (don’t try to update generated columns!)
* Fix: Add try/except to set_by_pk,
* Fix: In save_record use .to_dict() instead of dict() for pd.Series… dict() keeps ints as numpy types
* Display description column for sg.Text if a fk. skip sg.text in save_records
* Add readonly to add_column()
* Example to show different checkbox behavior: Boolean is the only one fully supported in celledit, while we do 'best-effort' for int/text
* display Booleans as checkboxes in sg.Tables

**Comment by PySimpleSQL** [comment]
Very cool - I look forward to seeing it.  Unfortunately I'm on a 100+ hour work week this week so I've been pretty pinned down

**Comment by ssweber** [comment]
Figured you we swamped! Just wanted to give an update :)

**Comment by ssweber** [comment]
Preview: Almost finished. Excited about this datepicker:

https://github.com/PySimpleSQL/pysimplesql/assets/57631333/0a2b1a85-4c14-404d-89e5-e757af0c5e6a

**Comment by PySimpleSQL** [comment]
Wow, sweet!

Sorry, I've been pinned down.  Looks like I have a ton to catch up on.
Sorry for the delay with things, time has been very slim this month!
