### ISSUE TITLE
Add data_key as 3rd arg of callbacks?

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#316]
I’d like to add a new callback, “current_row_updated” (name? after_current_update”?) that is called when celledit/LiveUpdate write changes to the rows df via set_current.

I figure you make use of callbacks in your own projects, so I wanted to ask if it’d be ok to add “data_key” as the third argument to all the callbacks. Right now only frm/window are passed. I believe this additional info would be helpful.

**Comment by PySimpleSQL** [comment]
Yeah, that sounds fine to me.  It would be nice if it were optional though
for reverse compatibility

**Comment by ssweber** [comment]
Ok, we will do something like this:

```python
import inspect

def invoke_callback(callback, *args):
    # Get the callback's signature
    signature = inspect.signature(callback)

    # Get the number of parameters in the signature
    num_params = len(signature.parameters)

    if num_params == 3:
        # Pass all three arguments if the callback expects three parameters
        callback(*args)
    elif num_params == 2:
        # Pass only the first two arguments if the callback expects two parameters
        callback(*args[:-1])
    else:
        # Handle the case if the callback expects a different number of parameters
        raise ValueError("Unexpected number of parameters in the callback function")
