### ISSUE TITLE
LazyTable

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#319]
@PySimpleSQL, havnt heard from you in a bit, but wanted to share my latest push to WIP, that I’m excited about. I’ve just been whittling away, so no worries if you currently don’t have time to review.

Now, by specifying ss.LazyTable as the element in a selector(), you can have a huge DataSet, with no lag!

Here’s the docstring:
```
The LazyTable is a subclass of sg.Table for improved performance by loading rows
    lazily during scroll events. Updating a sg.Table is generally fast, but with large
    DataSets that contain thousands of rows, there may be some noticeable lag. LazyTable
    overcomes this by only inserting only visible rows during an `update()` call.

**Comment by PySimpleSQL** [comment]
Awesome!  I was thinking of doing something similar eventually.  I haven't
been able to check it out yet, but I will as soon as I can figure out why
the WIP branch is bombing out on me

**Comment by ssweber** [comment]
I’m glad you like it. It’s cool to have an option if someone has like a massive table they arnt filtering down
