### ISSUE TITLE
Filtering Search Behavior

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#320]
What do you think about this as a alternative search behavior:

https://github.com/PySimpleSQL/pysimplesql/assets/57631333/d9ea88a8-a325-4306-b09b-5736b34bcbdb

**Comment by ssweber** [comment]
This is sorta what Thunderbird uses for its “quick filter”, which I find even more useful than its search function

Thunderbird persists the filter through sorts, only clearing it after leaving the folder and coming back.

So we could persist in through sg.Table sorts, but clear the search input during any requery.

**Comment by ssweber** [comment]
search_order in this context would most likely be better named “_search_columns” (although we could keep search_order as an alias), and search_columns could be a property that returns all columns if search_columns isn’t specified.

**Comment by ssweber** [comment]
If you want, this could be in addition to search+return == set to next result.

Current search behavior would never go to the next search_order column if the first has any results, did it? It just loops to beginning, correct?

**Comment by ssweber** [comment]
[This isn't that bad of a diff](https://github.com/PySimpleSQL/pysimplesql/pull/323/files). Would you want the combo/listbox/sliders filtered as well? I think it may just be a nice Table-view addition. This is the [filtering-search branch](https://github.com/PySimpleSQL/pysimplesql/tree/filtering_search)

I didn't try to keep the filter persistent through sorts/first/prev/next/last. I sorta like the behavior: 

https://github.com/PySimpleSQL/pysimplesql/assets/57631333/87ba3dca-4e0a-47c0-9642-b1bda8b9cea1

**Comment by ssweber** [comment]
However, the ability to keep clicking 'Return' is lost here.

Keeping it persistent is fairly easy. Will reset search during virtual pk insert, save, and requery?

**Comment by ssweber** [comment]
Updated:

https://github.com/PySimpleSQL/pysimplesql/assets/57631333/ee782512-c2f4-42ab-9216-5268e578d470

**Comment by ssweber** [comment]
After some consideration, I think adding this as a TableHeadings setting is appropriate… enable_search_filtering. I’ll set to False by default, like the other new ones in WIP.

That way it doesn’t change behavior unless desired.

**Comment by PySimpleSQL** [comment]
Yeah, I like the idea of it being optional, and TableHeadings seems to be
an appropriate place for it :)
