### ISSUE TITLE
prefix_data_keys & frm[rel…table]

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#322]
There are 19 spots in the code where we do: frm[rel…], referencing a dataset by its database table name.

This is fine, until someone uses prefixes. @PySimpleSQL do you use prefixes?

I bumped into this when I tried to use prefix_data_key in quick_editor. Need to think about how we want to fix this.

**Comment by PySimpleSQL** [comment]
Finally getting another quick breather to look at things.

I actually haven't used prefixes since very early in development.  I think
it could be a cool feature, but I'm not completely sure they are even
needed to be honest.

**Comment by ssweber** [comment]
I removed these in the WIP branch, until we want to tackle this in future
