### ISSUE TITLE
Screenshots from my branch

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#33]
Just wanted to show progress. These effects can be achieved by adding:

```
sg.change_look_and_feel('SystemDefaultForReal') # Closest I found to normal Windows 11 colors
ss.set_ttk_theme('xpnative') #available ones are 'winnative' 'clam' 'alt' 'default' 'classic' 'vista' 'xpnative'
ss.set_label_size(15, 1)
ss.set_element_size(40,1)
ss.set_mline_size(60,7)
icons = {
    'emoji': {
        'edit_protect' : f'\N{LOCK WITH INK PEN}',
        'quick_edit' : f'\N{LOWER LEFT BALLPOINT PEN}',
        'save' : f'\N{FLOPPY DISK}',
        'first' : f'\N{BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR}',
        'previous' : f'\N{LEFTWARDS BLACK ARROW}',
        'next' : f'\N{BLACK RIGHTWARDS ARROW}',
        'last' : f'\N{BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR}',
        'insert' : f'\N{HEAVY PLUS SIGN}',
        'delete' : f'\N{WASTEBASKET}',
        'search' : f'\N{LEFT-POINTING MAGNIFYING GLASS} Search',
        'duplicate' : f'\N{MAGIC WAND} Duplicate',
        }}
ss.load_iconpack(icons)
ss.set_iconpack('emoji')
```

Directly underneath the import pysimplesql as ss.

And then add change pysimplegui window call to:

`win = sg.Window('places to eat', layout, finalize=True, ttk_theme=ss.get_ttk_theme())`

Main screen:
![main_screen](https://user-images.githubusercontent.com/57631333/215182971-25d0cfd5-b491-44f5-9f00-a4bfb1875f46.png)

Save as quick_message that doesn't need an OK to close
![save](https://user-images.githubusercontent.com/57631333/215182974-6902d203-8226-4f49-a638-d56f05eb2f09.png)

Added 'Copy of' to duplicates
![Copy of](https://user-images.githubusercontent.com/57631333/215182976-00ce10b2-c49f-419b-92cb-cf14fc0997a2.png)

Duplicate/delete prompt only when there are children to duplicate/delete
![duplicate_prompt](https://user-images.githubusercontent.com/57631333/215182978-dd5a4327-4340-4de1-a3c7-3a92c3839bff.png)

**Comment by PySimpleSQL** [comment]
This looks great.  I really like that it allows for changing of the look
and feel quite easily.

I have some time off of work starting Monday, so l will be rolling these
changes in soon
