### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by Didymograptus** [PySimpleSQL/pysimplesql#342]
I've come across this library, which looks great. I have some SQL and pySinpleGUI experience. Is there anything I can do whilst getting to grips with the library, e.g. testing documentation etc. I also have some experience with mkDocs (Material).

I think this has great potential and would like to help it grow.

Tony

**Comment by ssweber** [comment]
Hi Tony!

The WIP branch is in pretty good shape (as far as bugs and functionality). Download it and give the journal or orders.py examples a try.

Unfortunately the original author isn’t responding - so I’m unable to release it to PyPi under the pysimplesql name. I’m available to fix any bugs you run into or answer any questions you have.

It really needs a simple Readme - and maybe your “fresh” experience with it could help. I really miss working with another person on it - that was half the fun! I’m game to get it to a position to release to PyPi under a new name (maybe pysimplesql-3 would be allowed?)

Long-term I’m more interested in a better way of structuring the functionality. I plan on making something similar in syntax to flask-appbuilder, but using tkinter + sqlalchemy. That would make it a much more solid foundation than our custom sql driver on top of pysimplegui (which is itself a wrapper on top of tkinter).

**Comment by Didymograptus** [comment]
Thanks for responding. I'll take a look at the WIP branch and the Readme.

Shame about the original author. Sounds like the repo needs to be forked.

I understand your point about restructuring, but I also like the simplicity/rapid dev you get with pySimpleGUI. I expect there is room to accommodate both in the long-term?

**Comment by ssweber** [comment]
Yes- we’ll need to fork and see about uploading as pysimplesql-3 or whatever PyPi allows. I’m really open to seeing however you’d like to contribute.

**Comment by PySimpleSQL** [comment]
Sorry, I'll get back to you ASAP.  It's been crazy all summer and I'm just
getting my first day off from work in over two months.  I'll get on
tomorrow and get the permissions sorted!

**Comment by ssweber** [comment]
Wow, its great to hear from you! Yeah, it'd be awesome to have the authority to merge into master - so whatever readme/docs we come up with can be easily found. And PyPi permissions so I can publish it. Docker permissions are less important.

The WIP orders.py example is alot of fun - loads of bells and whistles that make for a great presentation 😄

**Comment by ssweber** [comment]
FYI - so you don't have to watch 5 videos in WIP pull request - here's a consolidated version of where things are at:

https://github.com/PySimpleSQL/pysimplesql/assets/57631333/a4e6a7e3-ec50-472e-89dd-f325f8c93915

**Comment by Didymograptus** [comment]
WIP branch looks good so far. I'm up and running on a new install of Linux Mint 21.2 using PyCharm community. I'll also be using Win 10 occasionally.

**Comment by PySimpleSQL** [comment]
Sam- sorry it's so late, but it's been my only chance to get on here
today.  I removed the branch protection rules so you can get your changes
in.  I'll catch up with you soon - I'm excited to hear about the changes!

Thanks again

**Comment by ssweber** [comment]
Thanks Jon. That’ll help!

**Comment by Didymograptus** [comment]
I suggest that we close this issue and carry on talking about the repo/project in 'discussions'. https://github.com/PySimpleSQL/pysimplesql/discussions
Let's keep issues for bugs and wishlist items.

**Comment by ssweber** [comment]
alright 😄
