### ISSUE TITLE
Reduce setters, getters for variables - reducing function proliferation

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#39]
Your comment on keeping pysimplesql simple stuck with me.
I got thinking about all the setters/getters for variables.

set_label_size
set_element_size
set_mline_size
set_ttk_theme
get_ttk_theme - here people would just put ttk_theme=ss.get_ttk_theme()

_default_label_size = (15, 1), could become default_label_size, and it would be set as ss.default_label_size = 
default_element_size, default_mline_size, default_ttk_theme = 'default'

Future ones we might want:
default_duplicate_msg, default_save_msg, default_prompt_msg and so forth

Pro: Not many of these are used yet in projects. Less code lines.
Downside: Lose auto-documenting docstrings for each.

**Comment by PySimpleSQL** [comment]
Yeah, this is a tough one to call.  The pros and cons are pretty even on this!

**Comment by ssweber** [comment]
I'll close this for now, and reopen if/when message customization/localization gets discussed.
