### ISSUE TITLE
Extending/renaming iconpacks?

### ISSUE THREAD

**Issue by PySimpleSQL** [PySimpleSQL/pysimplesql#41]
Some thought and experimenting should go into extending iconpacks to include the ttktheme, sounds, etc.  Also a way to include default values so that it's quick and easy to make a simple iconpack with one custom aspect and the rest use some sane default.

With this kind of added functionality, it might make sense to rename from iconpack to themepack or some other descriptive version - a one-stop shop for changing the look and feel of pysimplesql

**Comment by ssweber** [comment]
I’m for this change!
