### ISSUE TITLE
Thoughts on child re-parenting itself

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#48]
I think it would be nice to provide a straight-forward way to change a child-record's parent. Right now, it works, but sometimes it stays in selection, or if its the last element selected, there is an IndexError.

My attempt at integrating it into the logic went something like:

- Modify records_changed to accept a single column
- In save_record, do a self.records_changed(r.fk)
- If changes, after save:
```
            if fk_changed:
                # we know that child is no longer under this parent, so move to previous.
                # TODO: How to fix when previous will do -2 if you change parent? Too rare to care?
                if self.current_index > 0: self.current_index -= 1
                # make sure to requery parent, but don't move to record. For grandchildren records.
                self.frm[self.frm.get_parent(self.table)].requery(select_first=False)
```
For the most part, it works. However, it's hard to stomp out all the bugs. And the child simply disappears from view, which is sorta weird.

So instead, I'm wondering what you think about the following:

- Modify records_changed to accept a single column (like update_elements). It would be column_name:str=None
- New function, get_requery_fk(), that returns result of:
```
            for qry in self.frm.queries:
                for r in self.frm.relationships:
                    if r.child == self.table:
                        fk_column = r.fk
```

- Then you could easily pass records_changed(fk), and get a True/False/None
- With that, create example [CHANGE PARENT] button that calls a popup (like quick-editor). Have parents with drop-down/search, and then question: 

1. Move child to parent, stay on current parent.
2. Move child to parent, switch to new parent
3. Discard changes.

What do you think?

#https://github.com/PySimpleSQL/pysimplesql/issues/43

**Comment by ssweber** [comment]
Now that requery_dependents is recursive in my branch, I think this would work:
```
if self.current_index > 0: self.current_index -= 1
self.frm[self.frm.get_parent(self.table)].requery(select_first=False)
self.frm[self.frm.get_parent(self.table)].requery_dependents()
self.frm.update_elements([self.frm.get_parent(self.table)]
```
I'll test out another day when I have some time.

**Comment by ssweber** [comment]
Above didn't work.

See https://github.com/PySimpleSQL/pysimplesql/commit/4522ebe792e0b88cb81c32b14f54a6600eba22f0 for what it would take to fix most issues. Getting r.fk and testing if fk_column has changed before saving could be split out into its own function, for cleanness sake.

**Comment by PySimpleSQL** [comment]
Can you provide a small example of this?

in theory it should be as easy as changing the foreign key to the new parent primary key, saving the changes and updating the elements.  I'd have to see a real example though, it probably will depend on how one goes about defining the parent<-> child relationship
