### ISSUE TITLE
IDEA - On Search, move scrollbar on sg.Table to highlighted element

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#55]
From 0-100, calculate where a row is in the list or rows. Then set:
```
len(self.rows)/self.current_index = percentage
table.set_vscroll_position(percentage)
```
See:
https://stackoverflow.com/questions/69149567/pysimplegui-table-is-there-a-get-or-set-type-feature-for-tables-vertical-scrol

**Comment by ssweber** [comment]
works pretty good, https://github.com/ssweber/pysimplesql/compare/revert_transform...ssweber:pysimplesql:set-vscroll-by-pk

**Comment by PySimpleSQL** [comment]
this looks pretty good for now

**Comment by ssweber** [comment]
Thanks!
