### ISSUE TITLE
How to set default row number? DBbrowser autoincrements from 1

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#58]
Pysimplesql assumes pk of tables start at 0. Dbbrowser autoincrements from 1. It threw me initially!

If yours start at 1, place a fmr['query-name'].requery() for the queries that arn't showing records initially.

Place after frm=ss.Form(':memory:',sql_commands=sql, bind=window).

**Comment by PySimpleSQL** [comment]
I haven't dug into this yet, but I don't recall this assumption.  It should just return results as set by the order clause.  Can you provide any more detail on this?

**Comment by ssweber** [comment]
I didn’t look into it much yet either.
See [My example](https://github.com/ssweber/pysimplesql-examples/blob/main/tests/parent%20child%20grandchild.py) 

run, then run again, commenting out the line 166… you’ll see that results don’t display initially.

I saw in the debug output that the initial pk for select * from…. Is 0
