### ISSUE TITLE
Toggle to display none if no parent

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#60]
Normal behavior is to filter children by parent. If no parents, but children, show children?

This issue is for me to investigate and potentially create toggle to not show children if they don’t have any parents.

It was confusing me, I had a parent/child/grandchild table — and when I created a new parent (with no children), then then all the grandchildren would show up. Well duh - it’s because they didn’t have any parents filtering them. But that only dawned on me now.

_Originally posted by @ssweber in https://github.com/PySimpleSQL/pysimplesql/issues/59#issuecomment-1427017701_

**Comment by PySimpleSQL** [comment]
That's an interesting case... I'm not sure what the most sane default would be to do honestly.

**Comment by ssweber** [comment]
I’ll experiment with some options. I’m sorta leaning towards a flag in query, show_parentless = True being the default.

**Comment by PySimpleSQL** [comment]
Cool thanks

It would be more fun to call it show_orphans :)

**Comment by ssweber** [comment]
Well, I guess they have parents, they are just estranged 😄 

See https://github.com/PySimpleSQL/pysimplesql/pull/65

**Comment by ssweber** [comment]
I’m going to look into requery_all. I think it should requery(select_first) first for parents, then their children, grandchildren, recursively.

Right now it just runs does for-loop through queries, and since selectors may or may not be updated yet, it might just grab the get_min_pk.

That’s fine, unless you have a grandchild with pk 1 that has fk to eg, child pk 2, instead of having a database that has parent 1, child 1, grandchild 1 all the same.

**Comment by ssweber** [comment]
https://github.com/PySimpleSQL/pysimplesql/pull/64/commits/cdb4aa9a1303b665f18794e3220f1e6d0f192c86
