### ISSUE TITLE
Investigate sg[element].get() stripping trailing whitespace

### ISSUE THREAD

**Issue by PySimpleSQL** [PySimpleSQL/pysimplesql#61]
PySimpleGUI element.get() seems to be stripping trailing whitespace (on multiline anyway).  For this reason, as a temporary workaround I started stripping trailing whitespace when loading from the database so that when saving a comparison can be made to decide whether or not there was a change (see commit 891414ef1b3bd61f353aedad2327e7bfd3a2148d)

**Comment by ssweber** [comment]
Googled it - see https://github.com/PySimpleGUI/PySimpleGUI/issues/6008#issuecomment-1302916222

**Comment by PySimpleSQL** [comment]
Thanks.  Now just to determine if we change the default setting when using
ss.record() or if it should just be a documented behavior and leave it to
the user to set the parameter

**Comment by PySimpleSQL** [comment]
I did some experimentation.  There currently isn't a great solution (without special tracking on the rstrip parameter being set by the user) on how to handle this. For example, if rstrip is set to true, then while reading in data we do the same rstrip on data coming from the database.  If rstrip is set to false, then anywhere we read from  sg.MLineget() we have to call get()[:1].

I think I'll leave it as is for now
