### ISSUE TITLE
Idea: Change examples to keep window invisible until right before while True:

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#67]
This hides the window redrawing as data is being populated:
```
window=sg.Window('Window Name', layout, finalize=True, grab_anywhere=True, alpha_channel=0)
frm=ss.Form(':memory:',sql_commands=sql, bind=window)   #<=== Here is the magic!
# put .set_where_clause, .set_order_clause, & requery's here
window.SetAlpha(1)
while True:
```

**Comment by ssweber** [comment]
See before and after.
https://user-images.githubusercontent.com/57631333/218806346-9bae8876-8e38-4ecc-9c69-ca54683f4a41.mp4

**Comment by PySimpleSQL** [comment]
Yea, we should show this in at least one example.  I personally like watching the form populate, but it's definitely not as professional looking

**Comment by ssweber** [comment]
Yeah, there is something nice about the populating. I used to lurk on KDE’s development, and there was always an ongoing discussion between presenting the screen as fast as possible, or when it was completely drawn.

**Comment by ssweber** [comment]
I think your progress bar handles this one
