### ISSUE TITLE
LanguagePack

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#79]
I’d like to go through and create central way to customize for all the popup messages, yes/no buttons, duplicate “Copy of”, etc.

Is that something that you would like to see added?

I guess the “right” way to do it would be to use gettext. [See example workflow](https://dev.to/michburkhalter/creating-a-python-app-with-translations-using-pysimplegui-and-babel-1lo0)

The other way would to mimic what I did with the icon pack, and put all the current texts in a dict, then replace in program with a simple namespace, eg msg.savedsuccess, msg.savednone. You get the picture.

My gut is to just go the iconpack route, since it’s not that many messages, and it’s so accessible for customization for newbies, versus gettext - which seems almost overkill. But I’d be willing to do it either way.

Opinion?

**Comment by PySimpleSQL** [comment]
Yeah,  I agree completely.   This is simple enough that a dictionary should
be able to provide localization as well as customization while keeping
things simple and lightweight

**Comment by ssweber** [comment]
Ok. I’ll go that direct then!

**Comment by ssweber** [comment]
Current plan was to make a MessagePack using your new ThemePack structure, and then go through replacing text in the code with ref to the msg.savenone, msg.savesucess..

Sound like a good plan?

**Comment by PySimpleSQL** [comment]
Yes,  that would be great!

Maybe just to keep things clean, derrive a new class from ThemePack

Class LanguagePack(ThemePack):...

If you need any kind of extra functionally it can be added to the new class

Personally, I think I would make the dict for English then push it through
Chat GPT and have all the languages done in a matter of minutes :)

**Comment by PySimpleSQL** [comment]
In fact, just to clean things up, I'm going to merge the ThemePack branch
down to abstract_database, then merge abstract_database down to development
and we can start working right in development again.    We are pretty far
along with the major changes, so I think the timing would be good

**Comment by ssweber** [comment]
ok, I'll wait till that's merged back down.

**Comment by PySimpleSQL** [comment]
It's all ready.l to go.  I created a stub for you to build off of :)

**Comment by ssweber** [comment]
Thanks for creating the stub. I’m going to do a bit more testing on all the changes… then start on this.

**Comment by ssweber** [comment]
#145 gets us pretty close.

How do you actually set a new one? I didn't look into that yet.

**Comment by ssweber** [comment]
I have them labled eg:

save_none # msg text
save_none_title # title text

if you think I should add _msg to the msg text ones, I'll go back and do that. I just got 'all-done' for the day.

**Comment by PySimpleSQL** [comment]
We will just pick back up tomorrow.  I'm done for the day too.  Just now
realized that I worked in the wrong branch all day (I've been trying to get
better about making new branches when trying new things), so now when I get
home sometime later I have a ton of conflicts to try to resolve.  My last
conflict experience did not go well at all

**Comment by PySimpleSQL** [comment]
Yeah,  that's what I think I did.

I will try researching the merging aspect of it later tonight and give it a
try.  I've grown by leaps and bounds in the last couple of months when it
comes to Git (having come from subversion) and collaboration (I've 9nly
ever worked on ym own projects), so I think I can get through it this time
without botching it up.

**Comment by ssweber** [comment]
The conflict is really small. Just me renaming langfrmt to langformat confused it, and it out your new progressbar class in the middle

**Comment by ssweber** [comment]
- [ ] add progress bar text
- [ ] Add “Copy of” text in
