### ISSUE TITLE
Idea: Expose column type, default, nullable

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#85]
If column_names was changed to a dict:

column_name = {
“name” : {
    “type” : type
    “default” : default
    “nullable” : nullable}}

it looks pretty straight-forward to add these while grabbing column names. Then change any current call to column_names to column_names.keys().

We could map types to Python types.
They could be used in Ajax-style validators
And defaults would be useful as a flag to populate inserts.

**Comment by PySimpleSQL** [comment]
Yeah, I like that a lot.  Maybe call it column_info to be more descriptive?

**Comment by ssweber** [comment]
Good idea. Would we change function names from column_name to column_info as well?
I figure while we're at it, probably would pass both our mapped python type, as well as original database type.

I might need help coming up with the mapping, as well as what to call the original vs converted type. sql_type/py_type?

For Sqlite
TEXT = str
NULL = '', empty string
```
def is_empty_string(value):
...     return str(value) == ''
```


INTEGER - int
REAL - float
BLOB - ?

**Comment by PySimpleSQL** [comment]
I think I'll implement this as a class.  It'll give more control and
unlimited direction in the future

**Comment by PySimpleSQL** [comment]
Since I think the database abstraction is all wrapped up, I think I might tackle this tomorrow.

There will still be some oddball cases to handle - as some default values are actually generated within the database (like current times and dates), so that'll be tricky to deal with.
