### ISSUE TITLE
Simple Transform / Default dictionary

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#90]
One thing I'd like to consider, especially now that default's are generated. A built-in 'simple transform' function.
I'm not sure how difficult this would be. But it would make a library user's life easier to just pop in how they'd like each value of a query acted on.

eg. (not real code)
```
frm['Journal'].set_transform(simple_transform)

frm['Journal'].add_simple_transform({'entry_date' : 
    {'decode' : datetime.utcfromtimestamp(int(row[col])).strftime('%m/%d/%y')),
    'encode' : datetime.strptime(row[col], '%m/%d/%y').replace(tzinfo=timezone.utc).timestamp()
     }

def add_simple_transform(transforms):
    for k in transforms.keys():
        if k not in _simple_transform.keys():
            _simple_transform |= transforms

## query level dict
_simple_transform = {}

def simple_transform(row,encode):
    for col, function in _simple_transform.items()
        if col in row:
            msg = f'Transforming {col} from {row[col]}'
            if encode == ss.TFORM_DECODE:
                row[col] = col['decode']
            else:
                row[col] = col['encode']
            logger.debug(f'{msg} to {row[col]}')

# Use our new transform!
frm['Journal'].requery()
```

Maybe like your comment, we could allow setting default values by just setting a value, instead of a function

**Comment by ssweber** [comment]
They could have multiple column names in the dict.

entry_date : encode function, decode function
name : {“default” : “New Person”, “encode” : col.capitalize()}

 Sorry, from my phone. But you get the idea.

**Comment by PySimpleSQL** [comment]
Yeah, I kind of like that more than the current transform system.

I think I'm going to add a null_defaults dictionary to ColumnInfo also and
set them to sane defaults, and give the user a way to change supply their
own dict.

 This may be my project for tomorrow (that and catching the MySql and
Postgres drivers to curdictionary.

I think after all of this it'll be time to merge back down to development
and do some cleanup and documentation for a release.  All of these have
been massive improvements

**Comment by PySimpleSQL** [comment]
I'll take a look as soon as i can.

Been struggling all day with something completely nonsensical and running
out of time pretty quickly

**Comment by ssweber** [comment]
Totally, no rush at all!

**Comment by PySimpleSQL** [comment]
Sorry I'm just getting back to this,  I only have a couple hours per day for a few more days before I get to another block of decent time.

Regarding defaults, we now have that taken care of with ColumnInfo.set_null_default() & ColumnInfo.set_null_defaults(), which support literal values and callables.

Regarding the simple transform, what are the advantages of this approach over the current transform that receives an entire row dict to act on vs. a simple transform that handles a single column in the row?

**Comment by PySimpleSQL** [comment]
Ok, I pulled in the changes.  I tried testing journal_with_data_manipuation.py but it is not working.  I want to give this a good test before getting rid of the old transform system

**Comment by ssweber** [comment]
Sorry, I thought I had it working before pulling!

Mainly saw it as a way to provide the boiler-plate for individual column transforms.

**Comment by ssweber** [comment]
Do you like how this ended up? I'll close if so.

**Comment by PySimpleSQL** [comment]
Yeah, I think we are good to go
