### ISSUE TITLE
Reducing pysimplegui .update() calls

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#98]
The slowdown I introduced, then fixed, with update_elements showed me that reducing .update() calls is worth investigating more. Especially beneficial in tabbed windows with lots of elements.

Id like to consider our own .update() which would store the previous element update call and only call pysimplegui’s update() if there was a change.

Cases we’d need to handle:

1. update(disabled=hide) Also would rename hide to disabled.
2. update(visible=True/False)
3. update(values=lst, set_to_index=table.current_index)
4.update(values=values,select_rows=index

update(value=table._current_index + 1, range=(1, l))

and possibly

set_vscroll_position()

**Comment by ssweber** [comment]
We could probably just add the checking logic in update_elements for everything except update(disabled=hide).

The case being that users usually wouldn’t handle their own marker/table/selector/slider/ logic, but may want to disable buttons based on conditions… like your save button TIMEOUT prompt_save example. If they called pysimplegui.update, but don’t update our cached state, then each update_elements would fight against them. So a frm.element_map[‘element’].disable(True/False) might make sense.

Otherwise, if we skip the new function calls and integrate the state-checking in update_elements, we would put in the save TIMEOUT example:

.update(disabled=disabled)
frm.element_map[‘element’].disable = disabled

**Comment by ssweber** [comment]
I think I convinced myself to have a element_state_cache dict that has:

- disabled - True/False
- visible - True/False
- listbox - [] of update call
- table - [] of update call
- spinner - [] of update call
- vscroll_position - Float

and is checked/populated on these calls. One dict for each element, values set to None initially, and then checked with a == and updated in update_elements for each update() call

**Comment by ssweber** [comment]
Before I do any of this, need to confirm that tkinter doesn’t already have its own cache.

**Comment by PySimpleSQL** [comment]
Yeah, I was going to suggest that some performance benchmarking needs done before getting too far into this, as complicating the codebase and changing the way a user would have to interact with the libraries wouldn't make sense if there is little to gain.  I have some very large complicated projects based on PySimpleGUI+pysimplesql and performance hasn't been an issue for me.  PySimpleGUI or tkinter could definitely already be doing this.

If benchmarking suggests that the performance improvements warrant caching, it might make more sense to derive a class from PySimpleGUI, and do the caching right in the element.update before calling super().update() - in this way it becomes automatic and completely transparent to the end user, then they can decide when they create their window if they want to use sg.Window(), or the cached ss.Window() version :)

**Comment by ssweber** [comment]
As usual, really good thoughts. I got worried about performance - so I’m glad to hear that you don’t see big lags in your apps.

**Comment by ssweber** [comment]
#100 was surprisingly effective.

I also tried checking the element.Disabled state before disabling all the record elements, but it had no affect on time.

**Comment by ssweber** [comment]
I changed all my selector sg.Table to sg.Combo, and there isn't any optimization worth there. 50 iterations run through in less than a second.

**Comment by ssweber** [comment]
Also texted listbox and slider. Only tables would benefit from the cache.

**Comment by ssweber** [comment]
Rethought it. #101 much simpler fix

**Comment by PySimpleSQL** [comment]
Thanks for putting effort into this

I'm going to be a little scarce for the next day or two, but the plan is to
let these small optimizations build here and pull them all in at once so we
can get a real comparison on overall improvement before and after.  I'd
like to finish up this abstract_database branch soon (probably later this
week) and start a new branch solely dedicated to the optimizations.  I'll
have quite a bit of time later this week, so I'll likely join you in
looking for areas to optimize!

**Comment by ssweber** [comment]
All good.

 I had gotten all excited about the idea of a cache, but It turned out the selector section needed the same `if table_name and q != table_name: continue` call. Nothing fancy 😊. 

It’s quite performant now, ~16 seconds to iterate 50 times, updating 4 table selectors each time.

**Comment by ssweber** [comment]
For future refactoring: 
We probably could split update_elements into a couple more functions..
and call
```
- already have = update_element_states
- update_element_action(table_name=table_name)
- update_element_record(table_name=table_name)
- update_element_selector(table_name=table_name)
```
to make it easier to reason about the logic.

**Comment by ssweber** [comment]
Optimization: Only update fk fields (eg combo dropdowns) associated with quick editor

**Comment by ssweber** [comment]
#148 using your omit_elements makes table sorting super fast!

**Comment by ssweber** [comment]
I think this one’s basically handled, closing
